// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inventory.proto

package com.example.Inventory;

public interface DecreaseItemQuantityRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:inventory.DecreaseItemQuantityRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>int64 quantity = 2;</code>
   * @return The quantity.
   */
  long getQuantity();
}
