// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inventory.proto

package com.example.Inventory;

public interface GetAllItemsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:inventory.GetAllItemsRequest)
    com.google.protobuf.MessageOrBuilder {
}
