// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inventory.proto

package com.example.Inventory;

public final class Inventory {
  private Inventory() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_inventory_CreateItemRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_inventory_CreateItemRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_inventory_CreateItemResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_inventory_CreateItemResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017inventory.proto\022\tinventory\"B\n\021CreateIt" +
      "emRequest\022\014\n\004name\030\001 \001(\t\022\020\n\010quantity\030\002 \001(" +
      "\003\022\r\n\005price\030\003 \001(\003\"?\n\022CreateItemResponse\022\016" +
      "\n\006status\030\001 \001(\003\022\r\n\005error\030\002 \001(\t\022\n\n\002id\030\003 \001(" +
      "\0032_\n\020InventoryService\022K\n\nCreateItem\022\034.in" +
      "ventory.CreateItemRequest\032\035.inventory.Cr" +
      "eateItemResponse\"\000B\031\n\025com.example.Invent" +
      "oryP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_inventory_CreateItemRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_inventory_CreateItemRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_inventory_CreateItemRequest_descriptor,
        new java.lang.String[] { "Name", "Quantity", "Price", });
    internal_static_inventory_CreateItemResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_inventory_CreateItemResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_inventory_CreateItemResponse_descriptor,
        new java.lang.String[] { "Status", "Error", "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
