// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inventory.proto

package com.example.Inventory;

public final class Inventory {
  private Inventory() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_inventory_CreateItemRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_inventory_CreateItemRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_inventory_CreateItemResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_inventory_CreateItemResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_inventory_GetItemRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_inventory_GetItemRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_inventory_GetItemData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_inventory_GetItemData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_inventory_GetItemResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_inventory_GetItemResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_inventory_GetAllItemsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_inventory_GetAllItemsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_inventory_GetAllItemsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_inventory_GetAllItemsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_inventory_UpdateItemRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_inventory_UpdateItemRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_inventory_UpdateItemResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_inventory_UpdateItemResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_inventory_DeleteItemRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_inventory_DeleteItemRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_inventory_DeleteItemResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_inventory_DeleteItemResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_inventory_DecreaseItemQuantityRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_inventory_DecreaseItemQuantityRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_inventory_DecreaseItemQuantityResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_inventory_DecreaseItemQuantityResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017inventory.proto\022\tinventory\"B\n\021CreateIt" +
      "emRequest\022\014\n\004name\030\001 \001(\t\022\020\n\010quantity\030\002 \001(" +
      "\003\022\r\n\005price\030\003 \001(\003\"?\n\022CreateItemResponse\022\016" +
      "\n\006status\030\001 \001(\003\022\r\n\005error\030\002 \001(\t\022\n\n\002id\030\003 \001(" +
      "\003\"\034\n\016GetItemRequest\022\n\n\002id\030\001 \001(\003\"H\n\013GetIt" +
      "emData\022\n\n\002id\030\001 \001(\003\022\014\n\004name\030\002 \001(\t\022\020\n\010quan" +
      "tity\030\003 \001(\003\022\r\n\005price\030\004 \001(\003\"V\n\017GetItemResp" +
      "onse\022\016\n\006status\030\001 \001(\003\022\r\n\005error\030\002 \001(\t\022$\n\004d" +
      "ata\030\003 \001(\0132\026.inventory.GetItemData\"\024\n\022Get" +
      "AllItemsRequest\"Z\n\023GetAllItemsResponse\022\016" +
      "\n\006status\030\001 \001(\003\022\r\n\005error\030\002 \001(\t\022$\n\004data\030\003 " +
      "\003(\0132\026.inventory.GetItemData\"N\n\021UpdateIte" +
      "mRequest\022\n\n\002id\030\001 \001(\003\022\014\n\004name\030\002 \001(\t\022\020\n\010qu" +
      "antity\030\003 \001(\003\022\r\n\005price\030\004 \001(\003\"Y\n\022UpdateIte" +
      "mResponse\022\016\n\006status\030\001 \001(\003\022\r\n\005error\030\002 \001(\t" +
      "\022$\n\004data\030\003 \001(\0132\026.inventory.GetItemData\"\037" +
      "\n\021DeleteItemRequest\022\n\n\002id\030\001 \001(\003\"3\n\022Delet" +
      "eItemResponse\022\016\n\006status\030\001 \001(\003\022\r\n\005error\030\002" +
      " \001(\t\";\n\033DecreaseItemQuantityRequest\022\n\n\002i" +
      "d\030\001 \001(\003\022\020\n\010quantity\030\002 \001(\003\"=\n\034DecreaseIte" +
      "mQuantityResponse\022\016\n\006status\030\001 \001(\003\022\r\n\005err" +
      "or\030\002 \001(\t2\370\003\n\020InventoryService\022K\n\nCreateI" +
      "tem\022\034.inventory.CreateItemRequest\032\035.inve" +
      "ntory.CreateItemResponse\"\000\022B\n\007GetItem\022\031." +
      "inventory.GetItemRequest\032\032.inventory.Get" +
      "ItemResponse\"\000\022N\n\013GetAllItems\022\035.inventor" +
      "y.GetAllItemsRequest\032\036.inventory.GetAllI" +
      "temsResponse\"\000\022K\n\nUpdateItem\022\034.inventory" +
      ".UpdateItemRequest\032\035.inventory.UpdateIte" +
      "mResponse\"\000\022K\n\nDeleteItem\022\034.inventory.De" +
      "leteItemRequest\032\035.inventory.DeleteItemRe" +
      "sponse\"\000\022i\n\024DecreaseItemQuantity\022&.inven" +
      "tory.DecreaseItemQuantityRequest\032\'.inven" +
      "tory.DecreaseItemQuantityResponse\"\000B\031\n\025c" +
      "om.example.InventoryP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_inventory_CreateItemRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_inventory_CreateItemRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_inventory_CreateItemRequest_descriptor,
        new java.lang.String[] { "Name", "Quantity", "Price", });
    internal_static_inventory_CreateItemResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_inventory_CreateItemResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_inventory_CreateItemResponse_descriptor,
        new java.lang.String[] { "Status", "Error", "Id", });
    internal_static_inventory_GetItemRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_inventory_GetItemRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_inventory_GetItemRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_inventory_GetItemData_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_inventory_GetItemData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_inventory_GetItemData_descriptor,
        new java.lang.String[] { "Id", "Name", "Quantity", "Price", });
    internal_static_inventory_GetItemResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_inventory_GetItemResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_inventory_GetItemResponse_descriptor,
        new java.lang.String[] { "Status", "Error", "Data", });
    internal_static_inventory_GetAllItemsRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_inventory_GetAllItemsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_inventory_GetAllItemsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_inventory_GetAllItemsResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_inventory_GetAllItemsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_inventory_GetAllItemsResponse_descriptor,
        new java.lang.String[] { "Status", "Error", "Data", });
    internal_static_inventory_UpdateItemRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_inventory_UpdateItemRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_inventory_UpdateItemRequest_descriptor,
        new java.lang.String[] { "Id", "Name", "Quantity", "Price", });
    internal_static_inventory_UpdateItemResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_inventory_UpdateItemResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_inventory_UpdateItemResponse_descriptor,
        new java.lang.String[] { "Status", "Error", "Data", });
    internal_static_inventory_DeleteItemRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_inventory_DeleteItemRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_inventory_DeleteItemRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_inventory_DeleteItemResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_inventory_DeleteItemResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_inventory_DeleteItemResponse_descriptor,
        new java.lang.String[] { "Status", "Error", });
    internal_static_inventory_DecreaseItemQuantityRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_inventory_DecreaseItemQuantityRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_inventory_DecreaseItemQuantityRequest_descriptor,
        new java.lang.String[] { "Id", "Quantity", });
    internal_static_inventory_DecreaseItemQuantityResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_inventory_DecreaseItemQuantityResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_inventory_DecreaseItemQuantityResponse_descriptor,
        new java.lang.String[] { "Status", "Error", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
